name: Docker Image CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
    
jobs:

  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Frontend Docker Image
      env:
        DOCKER_HUB_USERNAME: sorrykim
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: |
        docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_TOKEN
        cd client
        docker build -t sorrykim/basil:frontend .
        docker push sorrykim/basil:frontend
            
  build-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Backend Docker Image
      env:
        DOCKER_HUB_USERNAME: sorrykim  
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: |
        docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_TOKEN
        cd server
        docker build -t sorrykim/basil:backend .
